### ISSUE TITLE
Shader issue in non-browser mode

### ISSUE THREAD

**Issue by ghost** [mattdesl/three-shader-fxaa#2]
Thanks for fixing the demo. So I'm rendering from node, using three in a headless configuration. When I run from the browser, fxaa works great, but when run from node on the command line, I get

TypeError: string.replace is not a function
    at parseIncludes (/Users/.../node_modules/three/three.js:29083:17)
    at new WebGLProgram (/Users/.../node_modules/three/three.js:29386:18)
    at acquireProgram (/Users/.../node_modules/three/three.js:29819:14)
    at initMaterial (/Users/.../node_modules/three/three.js:25888:27)
    at setProgram (/Users/.../node_modules/three/three.js:26041:4)
    at renderBufferDirect (/Users/.../node_modules/three/three.js:25138:17)
    at renderObjects (/Users/.../node_modules/three/three.js:25822:11)
    at render (/Users/.../node_modules/three/three.js:25606:4)
    at Object.ShaderPass.render (/Users/.../node_modules/three-effectcomposer/lib/shaderpass.js:43:18)
    at Object.EffectComposer.render (/Users/.../node_modules/three-effectcomposer/index.js:70:14)

It looks like in three.js, in the WebGLProgram function:

```
return function WebGLProgram( renderer, code, material, parameters ) {

    var gl = renderer.context;

    var extensions = material.extensions;
    var defines = material.defines;

    var vertexShader = material.__webglShader.vertexShader;
    var fragmentShader = material.__webglShader.fragmentShader;
```

...

vertexShader is expected to be a string, and for my other shaders, it is, but for fxaa I get an object called DuplexWrapper:

DuplexWrapper {
  _readableState: 
   ReadableState {
     highWaterMark: 16,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
...

and so it seems to barf because it can't find a replace method on DuplexWrapper. Any idea what the issue might be? One difference is that, in headless mode, there is no global window object, so things have to be set up a little differently. Here is how i instantiate three:

```
window = { innerWidth: 800, innerHeight: 600 }

var canvas = { style : new Object() };
var gl = require('gl')(window.innerWidth, window.innerHeight);
var threegl = new THREE.WebGLRenderer(
{
    antialias : false,
    width: 0,
    height: 0,
    canvas: canvas,
    context: gl
});
```

This works well for everything so far, I can render in three, read the framebuffer into a buffer I can then write out to an image file, etc. But of course it's aliased, so this shader is exactly what I'm looking for. Thanks,

**Comment by mattdesl** [comment]
It's probably because this module uses glslify (in its deps) and is designed to be bundled with browserify (for the browser). When run through Node, the shaders are not inlined as they should be. I haven't tested or tried to support non-browserify/webpack usage.

To support, I would need to transpile the source on pre-publish – perhaps using something like [transpilify](https://github.com/livejs/transpilify).

**Comment by mattdesl** [comment]
I just pushed to master some changes that should work for your use case now. It relies on `build/index.js` which has the source inlined as strings. Let me know if that works! :smile:

**Comment by ghost** [comment]
I just copied index.js and package.json manually into node_modules/three-shader-fxaa, and it seems to be working :) I'm hoping you're good with making a release from this? Thanks!

**Comment by mattdesl** [comment]
Ok, pushed as 5.1.0. :smile:
